# Generated by Django 5.2.3 on 2025-06-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Author_Book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
